### ISSUE TITLE
Modify landing page + TODO

### ISSUE THREAD

**Issue by AnUnknownMiner** [AnUnknownMiner/PretendYoureXyzzy#1]
- [ ] Add Templar Logo
- [ ]  Remove unneeded text
- [ ]  Add CAH server to templargaming's domain.
- [ ]  Stress test site.
